[profile.default]
src = "src"
out = "out"
libs = ["lib"]
chain_id = 656476
rpc_url = "https://rpc.open-campus-codex.gelato.digital"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
